{{- range $routes := .Values.application.ingressRoutes }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $routes.name }}
  annotations:
{{ if eq $routes.type "istio" }}
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
{{- end }}
    kubernetes.io/ingress.class: nginx
{{- if $routes.subdomain }}
    subdomain: {{ $routes.subdomain.url }}
    inControllerIP: {{ $routes.subdomain.inControllerIP }}
{{- end }}
{{ if eq $routes.type "letsencript" }}
    cert-manager.io/cluster-issuer: "letsencrypt-production"
{{- end }}
spec:
  rules:
  - host: {{ $routes.name }}.{{ $routes.domainUrl }}
    http:
      paths:
      - pathType: Prefix
        path: "{{ $routes.path }}"
        backend:
          service:
            name: {{ $routes.service }}
            port:
              number: {{ $routes.port }}
{{- end }}
