apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}-svc
  labels:
    app: {{ .Values.application.name }}
{{- if .Values.application.svc.expose }}
    pool: {{ .Values.application.svc.expose.pool }}
{{ .Values.application.svc.expose.exposeLabel | indent 4 }}
{{- end }} 
spec:
  selector:
    app: {{ .Values.application.name }}
  ports:
{{- if .Values.application.svc.expose }}
{{- range $ports := .Values.application.svc.ports }}
  - name: {{ $ports.name }}-svc-port
    protocol: TCP
    port: {{ $ports.port }}
{{- end }}
  type: LoadBalancer
{{- else }} 
{{- range $ports := .Values.application.svc.ports }}
  - name: {{ $ports.name }}-svc-port
    protocol: TCP
    port: {{ $ports.port }}
    targetPort: {{ $ports.port }}
{{- end }}
{{- end }}